apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-email
spec:
  schedule: "0 23 * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: send-email
              image: "{REGISTRY_IMAGE}"
              command: ["npm", "run", "start:send-email"]
              env:
                - name: EMAIL_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: EMAIL_ADDRESS
                - name: EMAIL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: EMAIL_PASSWORD
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: DATABASE_URL
          restartPolicy: OnFailure
