apiVersion: batch/v1
kind: CronJob
metadata:
  name: send-email
spec:
  schedule: "0 23 * * *"
  concurrencyPolicy: Allow
  startingDeadlineSeconds: 100
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: ksa-cloud-sql
          containers:
            - name: send-email
              image: "REGISTRY_IMAGE}"
              command: ["npm", "run", "start:send-email"]
              env:
                - name: EMAIL_ADDRESS
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: EMAIL_ADDRESS
                - name: EMAIL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: EMAIL_PASSWORD
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: DATABASE_URL
                - name: DB_PORT
                  value: "5432"
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: USERNAME
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: PASSWORD
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      name: remember-me-api-secret
                      key: DATABASE
            - name: cloud-sql-proxy
              image: gcr.io/cloudsql-docker/gce-proxy:latest
              command:
                - "/cloud_sql_proxy"
                - "-instances=r{INSTANCE_CONNECTION_NAME}=tcp:5432"
              securityContext:
                runAsNonRoot: true
          restartPolicy: OnFailure
